/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * An enumeration.
 */
export enum ObjectType {
  ACCOUNT = 'account',
  APPROVAL = 'approval',
  APPROVAL_REQUEST = 'approval_request',
  APPROVAL_POLICY = 'approval_policy',
  MONITESCRIPT_PROCESS = 'monitescript_process',
  AUDIT_TRAIL = 'audit_trail',
  COMMENT = 'comment',
  COUNTERPART = 'counterpart',
  COUNTERPART_ADDRESS = 'counterpart_address',
  COUNTERPART_BANK_ACCOUNT = 'counterpart_bank_account',
  COUNTERPART_CONTACT_PERSON = 'counterpart_contact_person',
  COUNTERPART_PARTNER_METADATA = 'counterpart_partner_metadata',
  COUNTERPART_TAX_ID = 'counterpart_tax_id',
  COUNTERPART_VAT_ID = 'counterpart_vat_id',
  ENTITY = 'entity',
  ENTITY_BANK_ACCOUNT = 'entity_bank_account',
  ENTITY_SETTINGS = 'entity_settings',
  ENTITY_TOKEN = 'entity_token',
  ENTITY_USER = 'entity_user',
  ENTITY_USER_TOKEN = 'entity_user_token',
  ENTITY_VAT_IDS = 'entity_vat_ids',
  EXPORT = 'export',
  PARTNER = 'partner',
  PARTNER_INTERNAL_CONFIG = 'partner_internal_config',
  PARTNER_SETTINGS = 'partner_settings',
  PARTNER_TOKEN = 'partner_token',
  PAYABLE = 'payable',
  PAYABLE_LINE_ITEM = 'payable_line_item',
  PAYABLES_PURCHASE_ORDER = 'payables_purchase_order',
  PAYMENT = 'payment',
  PAYMENT_INTENT = 'payment_intent',
  PAYMENT_LINK = 'payment_link',
  PAYMENT_RECORD = 'payment_record',
  PAYMENT_REMINDER = 'payment_reminder',
  PRODUCT = 'product',
  RECEIVABLE = 'receivable',
  RECONCILIATION = 'reconciliation',
  RECURRENCE = 'recurrence',
  ROLE = 'role',
  TAG = 'tag',
  TODO_TASK = 'todo_task',
  TODO_TASK_MUTE = 'todo_task_mute',
  TRANSACTION = 'transaction',
  WEBHOOK = 'webhook',
  WORKFLOW = 'workflow',
  WORKFLOW_PIPELINE = 'workflow_pipeline',
  OVERDUE_REMINDER = 'overdue_reminder',
  EINVOICING = 'einvoicing',
}
