compressionLevel: mixed

defaultSemverRangePrefix: ~

enableGlobalCache: false

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.4.0.cjs

nmMode: classic
enableTransparentWorkspaces: true

packageExtensions:
  "@team-monite/eslint-plugin@*":
    dependencies:
      "@team-monite/eslint-plugin": "workspace:*"
