# Dockerfile.sdk-demo-nginx

ARG BASE_IMAGE
FROM ${BASE_IMAGE} as base

FROM nginx:1.25.1

RUN ln -snf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo "Europe/Berlin" > /etc/timezone

# Set the working directory
WORKDIR /app

# Copy the build artifacts from the "base" stage
COPY --from=base /app/packages/sdk-demo/build /app
