# Dockerfile.sdk-drop-in-nginx
FROM nginx:1.25.1

WORKDIR /app

COPY --from=sdk-drop-in /app/packages/sdk-drop-in/dist /app

RUN useradd -u 7000 -s /bin/bash app && \
    ln -snf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo "Europe/Berlin" > /etc/timezone

USER app
