/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * An enumeration.
 */
export enum PaymentAuthorisationTypes {
    DOMESTIC_PAYMENT = 'DOMESTIC_PAYMENT',
    DOMESTIC_INSTANT_PAYMENT = 'DOMESTIC_INSTANT_PAYMENT',
    DOMESTIC_VARIABLE_RECURRING_PAYMENT = 'DOMESTIC_VARIABLE_RECURRING_PAYMENT',
    DOMESTIC_SCHEDULED_PAYMENT = 'DOMESTIC_SCHEDULED_PAYMENT',
    DOMESTIC_PERIODIC_PAYMENT = 'DOMESTIC_PERIODIC_PAYMENT',
    INTERNATIONAL_PAYMENT = 'INTERNATIONAL_PAYMENT',
    INTERNATIONAL_SCHEDULED_PAYMENT = 'INTERNATIONAL_SCHEDULED_PAYMENT',
    INTERNATIONAL_PERIODIC_PAYMENT = 'INTERNATIONAL_PERIODIC_PAYMENT',
    BULK_PAYMENT = 'BULK_PAYMENT',
}
