/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * An enumeration.
 */
export enum TaxIDTypeEnum {
  AE_TRN = 'ae_trn',
  AU_ABN = 'au_abn',
  AU_ARN = 'au_arn',
  BG_UIC = 'bg_uic',
  BR_CNPJ = 'br_cnpj',
  BR_CPF = 'br_cpf',
  CA_BN = 'ca_bn',
  CA_GST_HST = 'ca_gst_hst',
  CA_PST_BC = 'ca_pst_bc',
  CA_PST_MB = 'ca_pst_mb',
  CA_PST_SK = 'ca_pst_sk',
  CA_QST = 'ca_qst',
  CH_VAT = 'ch_vat',
  CL_TIN = 'cl_tin',
  ES_CIF = 'es_cif',
  EU_OSS_VAT = 'eu_oss_vat',
  EU_VAT = 'eu_vat',
  GB_VAT = 'gb_vat',
  GE_VAT = 'ge_vat',
  HK_BR = 'hk_br',
  HU_TIN = 'hu_tin',
  ID_NPWP = 'id_npwp',
  IL_VAT = 'il_vat',
  IN_GST = 'in_gst',
  IS_VAT = 'is_vat',
  JP_CN = 'jp_cn',
  JP_RN = 'jp_rn',
  KR_BRN = 'kr_brn',
  LI_UID = 'li_uid',
  MX_RFC = 'mx_rfc',
  MY_FRP = 'my_frp',
  MY_ITN = 'my_itn',
  MY_SST = 'my_sst',
  NO_VAT = 'no_vat',
  NZ_GST = 'nz_gst',
  RU_INN = 'ru_inn',
  RU_KPP = 'ru_kpp',
  SA_VAT = 'sa_vat',
  SG_GST = 'sg_gst',
  SG_UEN = 'sg_uen',
  SI_TIN = 'si_tin',
  TH_VAT = 'th_vat',
  TW_VAT = 'tw_vat',
  UA_VAT = 'ua_vat',
  US_EIN = 'us_ein',
  ZA_VAT = 'za_vat',
  UNKNOWN = 'unknown',
}
