/**
 * All options of currency locales
 * Responsible for internationalised number
 *  and currency formatting.
 * `Monite` uses BCP 47 language tag standard
 *
 * @see {@link https://github.com/libyal/libfwnt/wiki/Language-Code-identifiers#0x0400---0x04ff} BCP 47 language tag standard
 */
export type CurrencyLocale =
  /** Arabic, Saudi Arabia */
  | 'ar-SA'

  /** Bulgarian, Bulgaria */
  | 'bg-BG'

  /** Catalan, Spain */
  | 'ca-ES'

  /** Chinese, Taiwan, Province of China */
  | 'zh-TW'

  /** Czech, Czech Republic */
  | 'cs-CZ'

  /** Danish, Denmark */
  | 'da-DK'

  /** German, Germany */
  | 'de-DE'
  | 'el-GR'

  /** English, United States */
  | 'en-US'
  | 'es-ES_tradnl'
  | 'fi-FI'
  | 'fr-FR'
  | 'he-IL'
  | 'hu-HU'
  | 'is-IS'
  | 'it-IT'
  | 'ja-JP'
  | 'ko-KR'
  | 'nl-NL'
  | 'nb-NO'
  | 'pl-PL'
  | 'pt-BR'
  | 'rm-CH'
  | 'ro-RO'
  | 'ru-RU'
  | 'hr-HR'
  | 'sk-SK'
  | 'sq-AL'
  | 'sv-SE'
  | 'th-TH'
  | 'tr-TR'
  | 'ur-PK'
  | 'id-ID'
  | 'uk-UA'
  | 'be-BY'
  | 'sl-SI'
  | 'et-EE'
  | 'lv-LV'
  | 'lt-LT'
  | 'tg-Cyrl-TJ'
  | 'fa-IR'
  | 'vi-VN'
  | 'hy-AM'
  | 'az-Latn-AZ'
  | 'eu-ES'
  | 'wen-DE'
  | 'mk-MK'
  | 'st-ZA'
  | 'ts-ZA'
  | 'tn-ZA'
  | 'ven-ZA'
  | 'xh-ZA'
  | 'zu-ZA'
  | 'af-ZA'
  | 'ka-GE'
  | 'fo-FO'
  | 'hi-IN'
  | 'mt-MT'
  | 'se-NO'
  | 'ms-MY'
  | 'kk-KZ'
  | 'ky-KG'
  | 'sw-KE'
  | 'tk-TM'
  | 'uz-Latn-UZ'
  | 'tt-RU'
  | 'bn-IN'
  | 'pa-IN'
  | 'gu-IN'
  | 'or-IN'
  | 'ta-IN'
  | 'te-IN'
  | 'kn-IN'
  | 'ml-IN'
  | 'as-IN'
  | 'mr-IN'
  | 'sa-IN'
  | 'mn-MN'
  | 'bo-CN'
  | 'cy-GB'
  | 'km-KH'
  | 'lo-LA'
  | 'my-MM'
  | 'gl-ES'
  | 'kok-IN'
  | 'mni'
  | 'sd-IN'
  | 'syr-SY'
  | 'si-LK'
  | 'chr-US'
  | 'iu-Cans-CA'
  | 'am-ET'
  | 'tmz'
  | 'ne-NP'
  | 'fy-NL'
  | 'ps-AF'
  | 'fil-PH'
  | 'dv-MV'
  | 'bin-NG'
  | 'fuv-NG'
  | 'ha-Latn-NG'
  | 'ibb-NG'
  | 'yo-NG'
  | 'quz-BO'
  | 'nso-ZA'
  | 'ba-RU'
  | 'lb-LU'
  | 'kl-GL'
  | 'ig-NG'
  | 'kr-NG'
  | 'gaz-ET'
  | 'ti-ER'
  | 'gn-PY'
  | 'haw-US'
  | 'so-SO'
  | 'ii-CN'
  | 'pap-AN'
  | 'arn-CL'
  | 'moh-CA'
  | 'br-FR'
  | 'ug-CN'
  | 'mi-NZ'
  | 'oc-FR'
  | 'co-FR'
  | 'gsw-FR'
  | 'sah-RU'
  | 'qut-GT'
  | 'rw-RW'
  | 'wo-SN'
  | 'prs-AF'
  | 'plt-MG'
  | 'gd-GB';
