export const ROUTES = {
  counterparts: '/counterparts',
  payables: '/payables',
  settings: '/settings',
  approvalPolicies: '/settings/approval-policies',
  approvalRequests: '/approval-requests',
  roles: '/settings/roles',
  tags: '/settings/tags',
  expenses: '/expenses',
  receivables: '/receivables',
  products: '/products',
  onboarding: '/onboarding',
  integrations: '/integrations',
  rolesApprovals: '/settings/roles-approvals',
};
