import { components } from '@/api';
import { I18n } from '@lingui/core';
import { t } from '@lingui/macro';

type VatType = {
  label: string;
  value: components['schemas']['VatIDTypeEnum'];
  countryCode?: string;
  placeholderText?: string;
  vatName: string;
};

export function getVatTypeList(i18n: I18n): VatType[] {
  return [
    {
      label: t(i18n)`Australian Business Number (AU ABN)`,
      value: 'au_abn',
      countryCode: 'AU',
      placeholderText: '51824753556',
      vatName: 'ABN',
    },
    {
      label: t(i18n)`Australian Taxation Office Reference Number`,
      value: 'au_arn',
      countryCode: 'AU',
      placeholderText: '518247535567',
      vatName: 'ARN',
    },
    {
      label: t(i18n)`European VAT number (Austria)`,
      value: 'eu_vat',
      countryCode: 'AT',
      placeholderText: 'ATU12345678',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Belgium)`,
      value: 'eu_vat',
      countryCode: 'BE',
      placeholderText: 'BE0123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Brazilian CNPJ number`,
      value: 'br_cnpj',
      countryCode: 'BR',
      placeholderText: '28.271.211/0001-88',
      vatName: 'CNPJ',
    },
    {
      label: t(i18n)`Brazilian CPF number`,
      value: 'br_cpf',
      countryCode: 'BR',
      placeholderText: '137.609.391-04',
      vatName: 'CPF',
    },
    {
      label: t(i18n)`Bulgaria Unified Identification Code`,
      value: 'bg_uic',
      countryCode: 'BG',
      placeholderText: '123456789',
      vatName: 'UIC',
    },
    {
      label: t(i18n)`European VAT number (Bulgaria)`,
      value: 'eu_vat',
      countryCode: 'BG',
      placeholderText: 'BG0123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Canadian BN`,
      value: 'ca_bn',
      countryCode: 'CA',
      placeholderText: '123456789',
      vatName: 'BN',
    },
    {
      label: t(i18n)`Canadian GST/HST number`,
      value: 'ca_gst_hst',
      countryCode: 'CA',
      placeholderText: '123456789RT0002',
      vatName: 'GST HST',
    },
    {
      label: t(i18n)`Canadian PST number (British Columbia)`,
      value: 'ca_pst_bc',
      countryCode: 'CA',
      placeholderText: 'PST-1234-5678',
      vatName: 'PST BC',
    },
    {
      label: t(i18n)`Canadian PST number (Manitoba)`,
      value: 'ca_pst_mb',
      countryCode: 'CA',
      placeholderText: '123456-7',
      vatName: 'PST MB',
    },
    {
      label: t(i18n)`Canadian PST number (Saskatchewan)`,
      value: 'ca_pst_sk',
      countryCode: 'CA',
      placeholderText: '1234567',
      vatName: 'PST SK',
    },
    {
      label: t(i18n)`Canadian QST number (Québec)`,
      value: 'ca_qst',
      countryCode: 'CA',
      placeholderText: '1234567890TQ1234',
      vatName: 'QST',
    },
    {
      label: t(i18n)`Chilean TIN`,
      value: 'cl_tin',
      countryCode: 'CL',
      placeholderText: '12.345.678-K',
      vatName: 'TIN',
    },
    {
      label: t(i18n)`European VAT number (Croatia)`,
      value: 'eu_vat',
      countryCode: 'HR',
      placeholderText: 'HR12345678912',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Cyprus)`,
      value: 'eu_vat',
      countryCode: 'CY',
      placeholderText: 'CY12345678Z',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Czech Republic)`,
      value: 'eu_vat',
      countryCode: 'CZ',
      placeholderText: 'CZ1234567890',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Denmark)`,
      value: 'eu_vat',
      countryCode: 'DK',
      placeholderText: 'DK12345678',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Estonia)`,
      value: 'eu_vat',
      countryCode: 'EE',
      placeholderText: 'EE123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European One Stop Shop VAT number for non-Union scheme`,
      value: 'eu_oss_vat',
      countryCode: 'EU',
      placeholderText: 'EU123456789',
      vatName: 'OSS VAT',
    },
    {
      label: t(i18n)`European VAT number (Finland)`,
      value: 'eu_vat',
      countryCode: 'FI',
      placeholderText: 'FI12345678',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (France)`,
      value: 'eu_vat',
      countryCode: 'FR',
      placeholderText: 'FRAB123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Georgian VAT`,
      value: 'ge_vat',
      countryCode: 'GE',
      placeholderText: '123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Germany)`,
      value: 'eu_vat',
      countryCode: 'DE',
      placeholderText: 'DE123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Greece)`,
      value: 'eu_vat',
      countryCode: 'GR',
      placeholderText: 'EL123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Hong Kong BR number`,
      value: 'hk_br',
      countryCode: 'HK',
      placeholderText: '12345678',
      vatName: 'BR',
    },
    {
      label: t(i18n)`Hungary tax number (adószám)`,
      value: 'hu_tin',
      countryCode: 'HU',
      placeholderText: '12345678-1-23',
      vatName: 'TIN',
    },
    {
      label: t(i18n)`European VAT number (Hungary)`,
      value: 'eu_vat',
      countryCode: 'HU',
      placeholderText: 'HU12345678912',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Icelandic VAT`,
      value: 'is_vat',
      countryCode: 'IS',
      placeholderText: '123456',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Indian GST number`,
      value: 'in_gst',
      countryCode: 'IN',
      placeholderText: '12ABCDE3456FGZH',
      vatName: 'GST',
    },
    {
      label: t(i18n)`Indonesian NPWP number`,
      value: 'id_npwp',
      countryCode: 'ID',
      placeholderText: '12.345.678.9-012.345',
      vatName: 'NPWP',
    },
    {
      label: t(i18n)`European VAT number (Ireland)`,
      value: 'eu_vat',
      countryCode: 'IE',
      placeholderText: 'IE1234567AB',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Israel VAT`,
      value: 'il_vat',
      countryCode: 'IL',
      placeholderText: '12345',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Italy)`,
      value: 'eu_vat',
      countryCode: 'IT',
      placeholderText: 'IT12345678912',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Japanese Corporate Number (Hōjin Bangō)`,
      value: 'jp_cn',
      countryCode: 'JP',
      placeholderText: '1234567891234',
      vatName: 'CN',
    },
    {
      label: t(
        i18n
      )`Japanese Registered Foreign Businesses' Registration Number (Tōroku Kokugai Jigyōsha no Tōroku Bangō)`,
      value: 'jp_rn',
      countryCode: 'JP',
      placeholderText: '12345',
      vatName: 'RN',
    },
    {
      label: t(
        i18n
      )`Kenya Revenue Authority Personal Identification Number (PIN)`,
      value: 'unknown',
      countryCode: 'KE',
      placeholderText: 'P123456789X',
      vatName: 'PIN',
    },
    {
      label: t(i18n)`European VAT number (Latvia)`,
      value: 'eu_vat',
      countryCode: 'LV',
      placeholderText: 'LV12345678912',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Liechtensteinian UID number`,
      value: 'li_uid',
      countryCode: 'LI',
      placeholderText: 'CHE123456789',
      vatName: 'UID',
    },
    {
      label: t(i18n)`European VAT number (Lithuania)`,
      value: 'eu_vat',
      countryCode: 'LT',
      placeholderText: 'LT123456789123',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Luxembourg)`,
      value: 'eu_vat',
      countryCode: 'LU',
      placeholderText: 'LU12345678',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Malaysian FRP number`,
      value: 'my_frp',
      countryCode: 'MY',
      placeholderText: '12345678',
      vatName: 'FRP',
    },
    {
      label: t(i18n)`Malaysian ITN`,
      value: 'my_itn',
      countryCode: 'MY',
      placeholderText: 'C 1234567890',
      vatName: 'ITN',
    },
    {
      label: t(i18n)`Malaysian SST number`,
      value: 'my_sst',
      countryCode: 'MY',
      placeholderText: 'A12-3456-78912345',
      vatName: 'SST',
    },
    {
      label: t(i18n)`European VAT number (Malta)`,
      value: 'eu_vat',
      countryCode: 'MT',
      placeholderText: 'MT12345678',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Mexican RFC number`,
      value: 'mx_rfc',
      countryCode: 'MX',
      placeholderText: 'ABC010203AB9',
      vatName: 'RFC',
    },
    {
      label: t(i18n)`European VAT number (Netherlands)`,
      value: 'eu_vat',
      countryCode: 'NL',
      placeholderText: 'NL123456789B12',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`New Zealand GST number`,
      value: 'nz_gst',
      countryCode: 'NZ',
      placeholderText: '123456789',
      vatName: 'GST',
    },
    {
      label: t(i18n)`Norwegian VAT number`,
      value: 'no_vat',
      countryCode: 'NO',
      placeholderText: '123456789MVA',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Pakistan National Tax Number (NTN) or Registration Number`,
      value: 'unknown',
      countryCode: 'PK',
      placeholderText: '4174941-3',
      vatName: 'NTN',
    },
    {
      label: t(i18n)`Philippines Taxpayer Identification Number (TIN)`,
      value: 'unknown',
      countryCode: 'PH',
      placeholderText: '000123456001',
      vatName: 'TIN',
    },
    {
      label: t(i18n)`European VAT number (Poland)`,
      value: 'eu_vat',
      countryCode: 'PL',
      placeholderText: 'PL1234567890',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Portugal)`,
      value: 'eu_vat',
      countryCode: 'PT',
      placeholderText: 'PT123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Romania)`,
      value: 'eu_vat',
      countryCode: 'RO',
      placeholderText: 'RO1234567891',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Russian INN`,
      value: 'ru_inn',
      countryCode: 'RU',
      placeholderText: '1234567891',
      vatName: 'INN',
    },
    {
      label: t(i18n)`Russian KPP`,
      value: 'ru_kpp',
      countryCode: 'RU',
      placeholderText: '123456789',
      vatName: 'KPP',
    },
    {
      label: t(i18n)`Saudi Arabia VAT`,
      value: 'sa_vat',
      countryCode: 'SA',
      placeholderText: '123456789012345',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Singaporean GST`,
      value: 'sg_gst',
      countryCode: 'SG',
      placeholderText: 'M12345678X',
      vatName: 'GST',
    },
    {
      label: t(i18n)`Singaporean UEN`,
      value: 'sg_uen',
      countryCode: 'SG',
      placeholderText: '123456789F',
      vatName: 'UEN',
    },
    {
      label: t(i18n)`European VAT number (Slovakia)`,
      value: 'eu_vat',
      countryCode: 'SK',
      placeholderText: 'SK1234567891',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Slovenia tax number (davčna številka)`,
      value: 'si_tin',
      countryCode: 'SI',
      placeholderText: '12345678',
      vatName: 'TIN',
    },
    {
      label: t(i18n)`European VAT number (Slovenia)`,
      value: 'eu_vat',
      countryCode: 'SI',
      placeholderText: 'SI12345678',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`South African VAT number`,
      value: 'za_vat',
      countryCode: 'ZA',
      placeholderText: '4123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Korean BRN`,
      value: 'kr_brn',
      countryCode: 'KR',
      placeholderText: '123-45-67890',
      vatName: 'BRN',
    },
    {
      label: t(i18n)`Spanish NIF number (previously Spanish CIF number)`,
      value: 'es_cif',
      countryCode: 'ES',
      placeholderText: 'A12345678',
      vatName: 'CIF',
    },
    {
      label: t(i18n)`European VAT number (Spain)`,
      value: 'eu_vat',
      countryCode: 'ES',
      placeholderText: 'ESA1234567Z',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`European VAT number (Sweden)`,
      value: 'eu_vat',
      countryCode: 'SE',
      placeholderText: 'SE123456789123',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Switzerland VAT number`,
      value: 'ch_vat',
      countryCode: 'CH',
      placeholderText: 'CHE-123.456.789 MWST',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Taiwanese VAT`,
      value: 'tw_vat',
      countryCode: 'TW',
      placeholderText: '12345678',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Thai VAT`,
      value: 'th_vat',
      countryCode: 'TH',
      placeholderText: '1234567891234',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Ukrainian VAT`,
      value: 'ua_vat',
      countryCode: 'UA',
      placeholderText: '123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`United Arab Emirates TRN`,
      value: 'ae_trn',
      countryCode: 'AE',
      placeholderText: '123456789012345',
      vatName: 'TRN',
    },
    {
      label: t(i18n)`United Kingdom VAT number`,
      value: 'gb_vat',
      countryCode: 'GB',
      placeholderText: 'GB123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Northern Ireland VAT number`,
      value: 'eu_vat',
      countryCode: 'GB',
      placeholderText: 'XI123456789',
      vatName: 'VAT ID',
    },
    {
      label: t(i18n)`Federal Tax Identification Number or EIN`,
      value: 'us_ein',
      countryCode: 'US',
      placeholderText: '12-3456789',
      vatName: 'EIN',
    },
    {
      label: t(i18n)`Other countries`,
      value: 'unknown',
      vatName: 'VAT ID',
    },
  ];
}
