name: Build Images and Deploy to Review

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - reopened

jobs:
  check-label:
    runs-on: ubuntu-latest
    outputs:
      has_label: ${{ steps.label-check.outputs.has_label }}
    steps:
      - name: Check for 'pullpreview' label
        id: label-check
        run: |
          labels=$(jq -r '.pull_request.labels | map(.name) | join(",")' "$GITHUB_EVENT_PATH")
          if [[ "$labels" == *"pullpreview"* ]]; then
            echo "has_label=true" >> "$GITHUB_OUTPUT"
            echo "pullpreview label found, proceeding with build and deploy"
          else
            echo "has_label=false" >> "$GITHUB_OUTPUT"
            echo "pullpreview label not found, skipping build and deploy"
          fi




  build-sdk-demo-with-nextjs-and-clerk-auth:
    name: Build and Push sdk-demo-with-nextjs-and-clerk-auth
    needs: check-label
    if: needs.check-label.outputs.has_label == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: werf/actions/install@v2
        with:
          version: v2.16.2

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.monite.com
          username: ${{ vars.GITLAB_BOT_USERNAME }}
          password: ${{ secrets.GITLAB_BOT_ACCESS_TOKEN }}

      - name: Build and Push All Images
        run: |
          . $(werf ci-env github --as-file)
          werf export \
            --config werf.nextjs-clerk.yaml \
            --parallel-tasks-limit=-1 \
            --repo registry.monite.com/monite/frontend/sdkapp \
            --tag registry.monite.com/monite/frontend/sdkapp:%image%-${{ github.sha }}

  build-sdk-drop-in:
    name: Build and Push sdk-drop-in
    needs: check-label
    if: needs.check-label.outputs.has_label == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: werf/actions/install@v2
        with:
          version: v2.16.2

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.monite.com
          username: ${{ vars.GITLAB_BOT_USERNAME }}
          password: ${{ secrets.GITLAB_BOT_ACCESS_TOKEN }}

      - name: Build and Push All Images
        run: |
          . $(werf ci-env github --as-file)
          werf export \
            --config werf.drop_in.yaml \
            --parallel-tasks-limit=-1 \
            --repo registry.monite.com/monite/frontend/sdkapp \
            --tag registry.monite.com/monite/frontend/sdkapp:%image%-${{ github.sha }}

  build-sdk-playground:
    name: Build and Push sdk-playground
    needs: check-label
    if: needs.check-label.outputs.has_label == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: werf/actions/install@v2
        with:
          version: v2.16.2

      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.monite.com
          username: ${{ vars.GITLAB_BOT_USERNAME }}
          password: ${{ secrets.GITLAB_BOT_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Create .env file and Build SDK Playground
        run: |
          # Create .env file from GitHub secrets
          cat > packages/sdk-playground/.env << EOF
          VITE_MONITE_ENTITY_ID=${{ secrets.VITE_MONITE_ENTITY_ID }}
          VITE_MONITE_ENTITY_USER_ID=${{ secrets.VITE_MONITE_ENTITY_USER_ID }}
          VITE_MONITE_PROJECT_CLIENT_ID=${{ secrets.VITE_MONITE_PROJECT_CLIENT_ID }}
          VITE_MONITE_PROJECT_CLIENT_SECRET=${{ secrets.VITE_MONITE_PROJECT_CLIENT_SECRET }}
          VITE_MONITE_API_URL=${{ secrets.VITE_MONITE_API_URL }}
          VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
          EOF

          # Build SDK Playground with .env file
          yarn build --filter='sdk-playground'

      - name: Build and Push Images
        run: |
          . $(werf ci-env github --as-file)
          werf export \
            --config werf.sdk-playground.yaml \
            --parallel-tasks-limit=-1 \
            --repo registry.monite.com/monite/frontend/sdkapp \
            --tag registry.monite.com/monite/frontend/sdkapp:%image%-${{ github.sha }}

  trigger-gitlab-deploy:
    name: Trigger GitLab Deployment to Review
    runs-on: ubuntu-latest
    needs:
      - build-sdk-demo-with-nextjs-and-clerk-auth
      - build-sdk-drop-in
      - build-sdk-playground
      - check-label

    steps:
      - name: Trigger GitLab Pipeline Deploy to Review
        id: trigger-pipeline
        run: |
          REPO="${{ secrets.GITLAB_REPOSITORY }}"
          PROJECT_ID="${{ secrets.GITLAB_GROUP_ID }}"
          GITLAB_TOKEN="${{ secrets.GITLAB_TRIGGER_TOKEN }}"

          SDK_DEMO_WITH_NEXTJS_AND_CLERK_AUTH="sdk-demo-with-nextjs-and-clerk-auth-${{ github.sha }}"
          SDK_DROP_IN_NGINX="sdk-drop-in-nginx-${{ github.sha }}"
          SDK_PLAYGROUND_NGINX="sdk-playground-nginx-${{ github.sha }}"
          NORMALIZED_GITHUB_BRANCH=$(echo "${{ github.head_ref }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | cut -c1-63)
          echo "normalized_branch_name=$NORMALIZED_GITHUB_BRANCH" >> "$GITHUB_OUTPUT"

          echo "sdk-demo-with-nextjs-and-clerk-auth = $SDK_DEMO_WITH_NEXTJS_AND_CLERK_AUTH"
          echo "sdk-drop-in-nginx = $SDK_DROP_IN_NGINX"
          echo "sdk-playground-nginx = $SDK_PLAYGROUND_NGINX"
          echo "$NORMALIZED_GITHUB_BRANCH"

          RESPONSE=$(curl --request POST \
            --form token="${GITLAB_TOKEN}" \
            --form ref="master" \
            --form "variables[GITHUB_SHA]=${{ github.sha }}" \
            --form "variables[SDK_DEMO_WITH_NEXTJS_AND_CLERK_AUTH]=${SDK_DEMO_WITH_NEXTJS_AND_CLERK_AUTH}" \
            --form "variables[SDK_DROP_IN_NGINX]=${SDK_DROP_IN_NGINX}" \
            --form "variables[SDK_PLAYGROUND_NGINX]=${SDK_PLAYGROUND_NGINX}" \
            --form "variables[NORMALIZED_GITHUB_BRANCH]=${NORMALIZED_GITHUB_BRANCH}" \
            --form "variables[GITHUB_BRANCH]=${{ github.head_ref }}" \
            --form "variables[CI_PIPELINE_SOURCE]=pipeline" \
            --form "variables[CI_ACTION]=review_deploy" \
            "https://${REPO}/api/v4/projects/${PROJECT_ID}/trigger/pipeline")

          PIPELINE_ID=$(echo "$RESPONSE" | jq -r '.id')
          echo "Created pipeline ID: $PIPELINE_ID"

          # Update pipeline name for better visibility
          curl --request PUT \
            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_PUT_TOKEN }}" \
            --data "name=🔄 Review Deploy from PR ${{ github.head_ref }}" \
            "https://${REPO}/api/v4/projects/${PROJECT_ID}/pipelines/${PIPELINE_ID}/metadata"

      - name: Comment on PR with Preview URLs
        uses: thollander/actions-comment-pull-request@v3
        env:
          NORMALIZED_GITHUB_BRANCH: ${{ steps.trigger-pipeline.outputs.normalized_branch_name }}
        with:
          message: |
            🚀 **Preview URLs are now available!** 🚀
            - [SDK Playground](https://sdk-pg-${{ env.NORMALIZED_GITHUB_BRANCH }}.review.monite.com)
            - [SDK Drop in](https://cdn-${{ env.NORMALIZED_GITHUB_BRANCH }}.review.monite.com)
            - [SDK with NextJS](https://demo-${{ env.NORMALIZED_GITHUB_BRANCH }}.review.monite.com)
          comment-tag: preview-comment
          mode: upsert
