name: "Setup Monorepo"
description: "Setup Node and Install dependencies."
runs:
  using: "composite"
  steps:
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v4
      with:
        cache: 'yarn'
        node-version: 18.x

    - name: Restore node_modules
      uses: actions/cache@v4
      with:
        path: |
          .yarn/install-state.gz
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-1

    - name: Install Dependencies
      shell: bash
      run: yarn install --immutable

    - name: Run Turborepo Remote Cache
      uses: dtinth/setup-github-actions-caching-for-turbo@v1.2.0
